name: ci

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false && !github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache platformio and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pip-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-pip-${{ hashFiles('platformio.ini') }}
            ${{ runner.os }}-platformio-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio==6.1.16
          pio --version

      - name: Build
        run: pio run

      - name: Static code analysis
        run: pio check --fail-on-defect high -e native

      - name: Unittests
        run: pio test -e unittest

      - name: Find and run examples
        run: bash ./examples/build.sh default_envs

  linter:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Format check.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify file format with clang-format
        uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: './src'
          extensions: 'h,hpp,c,cpp'
          clangFormatVersion: 14
